### ISSUE TITLE
Add api-key.txt file to GitHub

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Weather-App#4]
Rather than having the user create the key file, it would be a lot quicker and easier for the user if you made one ahead of time.  You can put text instructions in there too "Paste your key in this file.... get your keys by visiting ..."

**Comment by israel-dryer** [comment]
Good idea. Will do.

**Comment by israel-dryer** [comment]
I added the API Key to the file itself. I asked politely for users to change it to their own.
