### ISSUE TITLE
Keep accidentally clicking city name and then it becomes slow to close the city chooser

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Weather-App#5]
It's easy to click on the city name.  Once choosen, on my system it is taking several seconds to pull up the list and display it once I click the arrow on the listbox.

I've not looked at your code yet to see how the secondary window is being executed.  I was unable to close it using the escape key or the keyboard. I had to pull down the list and re-choose the city in order for the window to disappear.  

-------------

Semi-Related - location 

It  also creates the city chooser window in the default location.  After moving the weather window, it's kinda odd for the city chooser to show up in the middle of my main monitor.  Perhaps you can get the location of the window and pop-up the city chooser based on the location of the main window?

**Comment by israel-dryer** [comment]
I complete changed the UI on this... You now click a 'change the city' text an then enter either a zip code or city name to pull up a different city. Also, I did change the popup to show to the right of wherever the window currently is.
